In [ ]:
cart = {"apple": 3, "banana": 5}
cart["orange"] = 2
print(len(cart))

In [ ]:
cart = {"apple": 3, "banana": 5}

In [ ]:
cart

{'apple': 3, 'banana': 5}

In [ ]:
cart["orange"] = 2

In [ ]:
cart

{'apple': 3, 'banana': 5, 'orange': 2}

In [ ]:
len(cart)

3

In [ ]:
cart.get("apple")

3

In [ ]:
cart.get("kiwi", "not available")

'not available'

In [ ]:
total = 0
for i in range(1, 5):
    total += i
print(total)

In [ ]:
total = 0
for i in range(1, 5):
    total = total + i
print(total)

10

In [ ]:
for i in range(1,5):
  print(i)

1
2
3
4

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

(5,)

## Pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/churn_data.csv")

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,72,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,11,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,4,Yes,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,66,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

- Churn = No: The customer is active. The customer has not left the services
- Churn = Yes: The customer is inactive. The customer has left using the services.

In [ ]:
df.head()
# by defult you get top 5 rows

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df.head(10)

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,8,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,22,Yes,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,10,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,28,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,62,Yes,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [ ]:
df.tail()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,24,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,72,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,11,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,4,Yes,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,66,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
df.tail(10)

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7033,9767-FFLEM,38,Yes,Month-to-month,Yes,Credit card (automatic),69.50,2625.25,No
7034,0639-TSIQW,67,Yes,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes
7035,8456-QDAVC,19,Yes,Month-to-month,Yes,Bank transfer (automatic),78.70,1495.1,No
7036,7750-EYXWZ,12,No,One year,No,Electronic check,60.65,743.3,No
7037,2569-WGERO,72,Yes,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No
7038,6840-RESVB,24,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,72,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,11,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,4,Yes,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,66,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   tenure            7043 non-null   int64
 2   PhoneService      7043 non-null   object
 3   Contract          7043 non-null   object
 4   PaperlessBilling  7043 non-null   object
 5   PaymentMethod     7043 non-null   object
 6   MonthlyCharges    7043 non-null   float64
 7   TotalCharges      7043 non-null   object
 8   Churn             7043 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 495.3+ KB

- object === string/text
- int
- float
- bool
- datetime

In [ ]:
df

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,24,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,72,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,11,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,4,Yes,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,66,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
df.shape
# number of rows and columns

(7043, 9)

In [ ]:
df.columns

Index(['customerID', 'tenure', 'PhoneService', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=7043, step=1)

- df.head()
- df.tail()
- df.info()
- df.shape
- df.columns
- df.index

**Filter**

In [ ]:
df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df["Churn"]

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: object

In [ ]:
df[["Churn", "tenure"]]

     Churn  tenure
0       No       1
1       No      34
2      Yes       2
3       No      45
4      Yes       2
...    ...     ...
7038    No      24
7039    No      72
7040    No      11
7041   Yes       4
7042    No      66

[7043 rows x 2 columns]

- = : Assignment
- ==: Comparison

In [ ]:
a = 1
a == 1

True

In [ ]:
df["Churn"] == "Yes"

0       False
1       False
2        True
3       False
4        True
        ...
7038    False
7039    False
7040    False
7041     True
7042    False
Name: Churn, Length: 7043, dtype: bool

In [ ]:
df[df["Churn"] == "Yes"]

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,8,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
8,7892-POOKP,28,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
13,0280-XJGEX,49,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes
...,...,...,...,...,...,...,...,...,...
7021,1699-HPSBG,12,Yes,One year,Yes,Electronic check,59.80,727.8,Yes
7026,8775-CEBBJ,9,Yes,Month-to-month,Yes,Bank transfer (automatic),44.20,403.35,Yes
7032,6894-LFHLY,1,Yes,Month-to-month,Yes,Electronic check,75.75,75.75,Yes
7034,0639-TSIQW,67,Yes,Month-to-month,Yes,Credit card (automatic),102.95,6886.25,Yes
7041,8361-LTMKD,4,Yes,Month-to-month,Yes,Mailed check,74.40,306.6,Yes

In [ ]:
df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df['PhoneService'] == 'Yes'

0       False
1        True
2        True
3       False
4        True
        ...
7038     True
7039     True
7040    False
7041     True
7042     True
Name: PhoneService, Length: 7043, dtype: bool

In [ ]:
df[df['PhoneService'] == 'Yes'].shape

(6361, 9)

In [ ]:
len(df[df['PhoneService'] == 'Yes'])

6361

In [ ]:
df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

- Find number of customers using Mailed Check as the payment method

In [ ]:
df['PaymentMethod'] == "Mailed check"

0       False
1        True
2        True
3       False
4       False
        ...
7038     True
7039    False
7040    False
7041     True
7042    False
Name: PaymentMethod, Length: 7043, dtype: bool

In [ ]:
df[df['PaymentMethod'] == "Mailed check"].shape

(1612, 9)

**Multiple Conditions**

In [ ]:
(df['Churn'] == 'No') & (df['PhoneService'] == 'Yes')

0       False
1        True
2       False
3       False
4       False
        ...
7038     True
7039     True
7040    False
7041    False
7042     True
Length: 7043, dtype: bool

In [ ]:
df[(df['Churn'] == 'No') & (df['PhoneService'] == 'Yes')].shape

(4662, 9)

In [ ]:
df[(df['Churn'] == 'No') & (df['PhoneService'] == 'Yes')]['customerID'].nunique()

4662

In [ ]:
df1 = df[(df['Churn'] == 'No') & (df['PhoneService'] == 'Yes')]

In [ ]:
df1['customerID'].nunique()

4662

In [ ]:
df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

- Find the number of churn customer who left the company before 2 months of the tenure.

In [ ]:
(df['Churn'] == 'Yes') & (df['tenure'] < 2)

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7043, dtype: bool

In [ ]:
df[(df['Churn'] == 'Yes') & (df['tenure'] < 2)].shape

(380, 9)

**Aggregate**
- Group
- Aggregate

In [ ]:
df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df.groupby("Churn").agg({"customerID": "count"})

       customerID
Churn
No           5174
Yes          1869

In [ ]:
df.groupby("Churn")

In [ ]:
df.groupby("Churn").agg({"tenure":"mean", "customerID":"count"})

          tenure  customerID
Churn
No     37.569965        5174
Yes    17.979133        1869

In [ ]:
df.groupby("Churn").agg(avg_tenure=("tenure", "mean"), Count_of_customers=("customerID", "count"))

       avg_tenure  Count_of_customers
Churn
No      37.569965                5174
Yes     17.979133                1869

In [ ]:
df.groupby("Churn")['customerID'].count()

Churn
No     5174
Yes    1869
Name: customerID, dtype: int64

In [ ]:
cust = pd.read_csv("/content/customer_data.csv")
cust.head()

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

In [ ]:
df.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df2 = pd.merge(df, cust, on = "customerID", how = "inner")

In [ ]:
# final = pd.merge(df2, internet, on = , how = )

In [ ]:
df2.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender,SeniorCitizen,Partner,Dependents
0,7590-VHVEG,1,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,Female,0,Yes,No
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No,Male,0,No,No
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,Male,0,No,No
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,Male,0,No,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,Female,0,No,No

- Which gender has a higher avg monthly charges?

In [ ]:
df2.groupby("gender").agg({"MonthlyCharges":'mean'})

        MonthlyCharges
gender
Female       65.204243
Male         64.327482

- Among all churn customers, which payment method was popular?

In [ ]:
df['Churn']=='Yes'

0       False
1       False
2        True
3       False
4        True
        ...
7038    False
7039    False
7040    False
7041     True
7042    False
Name: Churn, Length: 7043, dtype: bool

In [ ]:
ch = df2[df2['Churn']=='Yes']
# ch =  the dataframe of all the churn customers

In [ ]:
ch.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,gender,SeniorCitizen,Partner,Dependents
2,3668-QPYBK,2,Yes,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,Male,0,No,No
4,9237-HQITU,2,Yes,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,Female,0,No,No
5,9305-CDSKC,8,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,Female,0,No,No
8,7892-POOKP,28,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,Female,0,Yes,No
13,0280-XJGEX,49,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,Male,0,No,No

In [ ]:
ch.groupby("PaymentMethod").agg({"customerID":"count"})

                           customerID
PaymentMethod
Bank transfer (automatic)         258
Credit card (automatic)           232
Electronic check                 1071
Mailed check                      308

- Which Contract type is popular among those who are male and have not churned?

In [ ]:
(df2['gender'] =='Male') & (df2['Churn'] == 'No')

0       False
1        True
2       False
3        True
4       False
        ...
7038     True
7039    False
7040    False
7041    False
7042     True
Length: 7043, dtype: bool

In [ ]:
b = df[(df2['gender'] =='Male') & (df2['Churn'] == 'No')]

In [ ]:
b.head()

,customerID,tenure,PhoneService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1,5575-GNVDE,34,Yes,One year,No,Mailed check,56.95,1889.5,No
3,7795-CFOCW,45,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
6,1452-KIOVK,22,Yes,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
9,6388-TABGU,62,Yes,One year,No,Bank transfer (automatic),56.15,3487.95,No
10,9763-GRSKD,13,Yes,Month-to-month,Yes,Mailed check,49.95,587.45,No

In [ ]:
b['Contract'].value_counts()
# groups, counts, sorts

Contract
Month-to-month    1137
Two year           824
One year           664
Name: count, dtype: int64

##Quiz

In [ ]:
user = pd.read_csv("/content/Users.csv")
rest = pd.read_csv("/content/Restaurant.csv")
order = pd.read_csv("/content/Orders.csv")
menu = pd.read_csv("/content/Menu.csv")
food = pd.read_csv("/content/Food.csv")

In [ ]:
user.head()

   User_id               Name  Age  Gender Marital Status Occupation
0        1    Claire Ferguson   20  Female         Single    Student
1        2     Jennifer Young   24  Female         Single    Student
2        3  Jermaine Roberson   22    Male         Single    Student
3        4   Rachel Carpenter   22  Female         Single    Student
4        5       Shawn Parker   22    Male         Single    Student

In [ ]:
user['Occupation'].value_counts()

Occupation
Student           53357
Employee          30408
Self Employeed    13913
House wife         2322
Name: count, dtype: int64

In [ ]:
rest.head()

,Restaurant_id,Name,Country,City,Rating,Rating_count,Cuisine
0,567335,AB FOODS POINT,India,Abohar,--,Too Few Ratings,"Beverages,Pizzas"
1,531342,Janta Sweet House,India,Abohar,4.4,50+ ratings,"Sweets,Bakery"
2,158203,theka coffee desi,India,Abohar,3.8,100+ ratings,Beverages
3,187912,Singh Hut,India,Abohar,3.7,20+ ratings,"Fast Food,Indian"
4,543530,GRILL MASTERS,India,Abohar,--,Too Few Ratings,"Italian-American,Fast Food"

In [ ]:
rest['City'].value_counts()

City
Bikaner                 1666
Noida-1                 1427
Indirapuram,Delhi       1279
BTM,Bangalore           1161
Rohini,Delhi            1135
                        ...
Alwarpet,Chennai           1
BBK_Chattarpur,Delhi       1
BBK_MayurVihar,Delhi       1
Hampi                      1
Manali                     1
Name: count, Length: 821, dtype: int64

In [ ]:
food.head()

  Food_id                  Item Food_Type
0     fd0     Aloo Tikki Burger       Veg
1     fd1     Veg Creamy Burger       Veg
2     fd2   Cheese Burst Burger       Veg
3     fd3  Paneer Creamy Burger       Veg
4     fd4        Maxican Burger       Veg

In [ ]:
food['Food_Type'].value_counts(normalize=True)

Food_Type
Veg        0.728749
Non-veg    0.271251
Name: proportion, dtype: float64

In [ ]:
order.head()

   order_date  Sales_QTY  Sales_amount currency  User_id  Restaurant_id
0  2017-10-10        100         41241      INR    49226       567335.0
1  2018-05-08          3            -1      INR    77359       531342.0
2  2018-04-06          1           875      INR     5321       158203.0
3  2018-04-11          1           583      INR    21343       187912.0
4  2018-06-18          6          7176      INR    75378       543530.0

In [ ]:
order['Sales_amount']>0

0          True
1         False
2          True
3          True
4          True
          ...
150276     True
150277     True
150278     True
150279     True
150280     True
Name: Sales_amount, Length: 150281, dtype: bool

In [ ]:
order[order['Sales_amount']>0]['Sales_amount'].mean()

np.float64(6635.938777157463)

In [ ]:
user.head()

   User_id               Name  Age  Gender Marital Status Occupation
0        1    Claire Ferguson   20  Female         Single    Student
1        2     Jennifer Young   24  Female         Single    Student
2        3  Jermaine Roberson   22    Male         Single    Student
3        4   Rachel Carpenter   22  Female         Single    Student
4        5       Shawn Parker   22    Male         Single    Student

In [ ]:
user['User_id'].nunique()

100000

In [ ]:
order.head()

   order_date  Sales_QTY  Sales_amount currency  User_id  Restaurant_id
0  2017-10-10        100         41241      INR    49226       567335.0
1  2018-05-08          3            -1      INR    77359       531342.0
2  2018-04-06          1           875      INR     5321       158203.0
3  2018-04-11          1           583      INR    21343       187912.0
4  2018-06-18          6          7176      INR    75378       543530.0

In [ ]:
order['User_id'].nunique()

77929

In [ ]:
uo = pd.merge(user, order, on = 'User_id', how = 'right')

In [ ]:
100000-77929

22071

In [ ]:
uo['User_id'].nunique()

77929

In [ ]:
len(set(user['User_id']) - set(order['User_id']))

22071

In [ ]:
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(left: 'DataFrame | Series', right: 'DataFrame | Series', how: 'MergeHow' = 'inner', on: 'IndexLabel | AnyArrayLike | None' = None, left_on: 'IndexLabel | AnyArrayLike | None' = None, right_on: 'IndexLabel | AnyArrayLike | None' = None, left_index: 'bool' = False, right_index: 'bool' = False, sort: 'bool' = False, suffixes: 'Suffixes' = ('_x', '_y'), copy: 'bool | None' = None, indicator: 'str | bool' = False, validate: 'str | None' = None) -> 'DataFrame'
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    left : DataFrame or named Series
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
    on : label or list
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : label or list, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : label or list, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default True
        If False, avoid copy if possible.

        .. note::
            The `copy` keyword will change behavior in pandas 3.0.
            `Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            will be enabled by default, which means that all methods with a
            `copy` keyword will use a lazy copy mechanism to defer the copy and
            ignore the `copy` keyword. The `copy` keyword will be removed in a
            future version of pandas.

            You can already get the future behavior and improvements through
            enabling copy on write ``pd.options.mode.copy_on_write = True``
    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  bar        2  bar        6
    3  baz        3  baz        7
    4  foo        5  foo        5
    5  foo        5  foo        8

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  bar           2  bar            6
    3  baz           3  baz            7
    4  foo           5  foo            5
    5  foo           5  foo            8

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8